Acme\Component\Hotel\Model\Room:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            serialized_name: id
        name:
            expose: true
            serialized_name: name
